import type { Metadata } from "next";
import { Playfair_Display, Montserrat } from "next/font/google";
import Image from "next/image";
import { Footer } from "@/components/Footer";
import "./globals.css";
import "../styles/luxury.css";

const playfair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${playfair.variable} ${montserrat.variable} antialiased bg-slate-950 font-sans relative min-h-screen`}
      >
        {/* Global Background */}
        <div className="fixed inset-0 z-0">
          <Image
            src="/bg-hero-final.png"
            alt="Cinematic Background"
            fill
            quality={100}
            priority
            className="object-cover opacity-40 mix-blend-overlay"
          />
          <div className="absolute inset-0 bg-[#050505]/70" />
          <div className="absolute inset-0 bg-gradient-to-t from-[#050505] via-transparent to-[#1A1612]/20" />
        </div>



        <div className="relative z-10">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
