import { Navbar } from "@/components/Navbar";

export default function TermsPage() {
    return (
        <main className="min-h-screen bg-[#050505] text-slate-300 pt-32 pb-32">
            <Navbar />

            <div className="max-w-3xl mx-auto px-6">

                {/* Header Section */}
                <div className="mb-16 border-b border-white/10 pb-8">
                    <span className="text-[#D4AF37] text-xs font-sans uppercase tracking-[0.2em] mb-4 block">Legal & Compliance</span>
                    <h1 className="text-4xl md:text-5xl font-serif text-white mb-4">Terms of Service</h1>
                    <p className="text-slate-400 font-sans text-sm tracking-wide">Last Updated: October 2026</p>
                </div>

                {/* Content */}
                <div className="prose prose-invert prose-slate max-w-none font-sans text-base leading-relaxed space-y-8">

                    <section>
                        <h2 className="text-2xl font-serif text-[#D4AF37] mb-4">1. Intelligence-Only Clause</h2>
                        <p>
                            TitleGuard AI is an intelligence and analytics accelerator, <strong>not a system of record</strong>. We provide actionable insights, quantitative risk assessments, and pre-underwriting analysis without assuming the data liability of long-term storage or archiving.
                        </p>
                        <p>
                            Our service is designed to complement your existing secure compliance workflows by delivering "intelligence only." By utilizing our platform, you acknowledge and agree that TitleGuard AI does not retain, archive, or back up your uploaded documents. It is strictly your responsibility to maintain permanent copies of all transaction materials within your own secure, firm-approved systems.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-serif text-white mb-4">2. Not Legal Advice</h2>
                        <p>
                            The output generated by the TitleGuard AI "Stoplight Report" and associated reasoning engines is for informational and workflow-acceleration purposes only. It does not constitute formal legal counsel, official title insurance underwriting, or a binding guarantee of a "Clear to Close" status.
                        </p>
                        <p>
                            You must rely solely on your appointed Title Officer, Underwriter, and Real Estate Attorney for final legal determinations regarding clouds on title, encumbrances, and curative requirements.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-serif text-white mb-4">3. Authorized Use</h2>
                        <p>
                            Access to the TitleGuard PRO AI platform is restricted to licensed real estate professionals, brokerages, and verified title entities. You agree not to reverse-engineer, exploit, or attempt to extract the underlying prompts or architecture of our Intelligence Engine.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-serif text-white mb-4">4. Limitation of Liability</h2>
                        <p>
                            To the maximal extent permitted by applicable law, TitleGuard PRO AI shall not be liable for any delayed closings, lost commissions, or damages arising from reliance on the platform's analysis. The platform is provided "as is," serving as a sophisticated secondary audit tool, not a primary guarantor of title integrity.
                        </p>
                    </section>

                </div>

                {/* Footer Contact */}
                <div className="mt-24 pt-8 border-t border-white/10">
                    <p className="text-sm font-sans text-slate-400">
                        For legal inquiries or enterprise licensing agreements, please contact our Legal Department via the Vault: <br />
                        <a href="mailto:concierge@titleguard-pro.ai" className="text-[#D4AF37] hover:text-white transition-colors tracking-wide mt-2 inline-block">concierge@titleguard-pro.ai</a>
                    </p>
                </div>
            </div>
        </main>
    );
}
